from django.conf import settings

"""
All status labels defined here.
"""
PENDING_STATUS = 'IP'
APPROVED_STATUS = 'AP'
CHALLENGED_STATUS = 'CH'

PENDING_DESCR = "Pending"
APPROVED_DESCR = "Approved"
CHALLENGED_DESCR = "Challenged"

STATUS_DICT = {
    PENDING_STATUS: PENDING_DESCR,
    APPROVED_STATUS: APPROVED_DESCR,
    CHALLENGED_STATUS: CHALLENGED_DESCR
}

MODERATOR_LIST = getattr(settings, "MONITOR_MODERATOR_LIST", [])